import * as Yup from "yup";

const formSchema = Yup.object().shape({
  characterDeathChoices: Yup.object().shape({
    astark: Yup.string().required("Required"),
      bdondarrion: Yup.string().required("Required"),
      bstark: Yup.string().required("Required"),
      btarth: Yup.string().required("Required"),
      bronn: Yup.string().required("Required"),
      clannister: Yup.string().required("Required"),
      dnaharis: Yup.string().required("Required"),
      dtargaryen: Yup.string().required("Required"),
      dseaworth: Yup.string().required("Required"),
      dedd: Yup.string().required("Required"),
      drogon: Yup.string().required("Required"),
      etully: Yup.string().required("Required"),
      egreyjoy: Yup.string().required("Required"),
      gendry: Yup.string().required("Required"),
      ghost: Yup.string().required("Required"),
      gilly: Yup.string().required("Required"),
      gclegane: Yup.string().required("Required"),
      greyworm: Yup.string().required("Required"),
      jlannister: Yup.string().required("Required"),
      jsnow: Yup.string().required("Required"),
      jmormont: Yup.string().required("Required"),
      lyanna: Yup.string().required("Required"),
      melisandre: Yup.string().required("Required"),
      missandei: Yup.string().required("Required"),
      nymeria: Yup.string().required("Required"),
      ppayne: Yup.string().required("Required"),
      qyburn: Yup.string().required("Required"),
      rhaegal: Yup.string().required("Required"),
      rarryn: Yup.string().required("Required"),
      babysam: Yup.string().required("Required"),
      starly: Yup.string().required("Required"),
      sclegane: Yup.string().required("Required"),
      sstark: Yup.string().required("Required"),
      nightking: Yup.string().required("Required"),
      tgreyjoy: Yup.string().required("Required"),
      tgiantsbane: Yup.string().required("Required"),
      tlannister: Yup.string().required("Required"),
      varys: Yup.string().required("Required"),
      ygreyjoy: Yup.string().required("Required"),
  }),
  betChoices: Yup.object().shape({
    jonIsAegon: Yup.string().required("Required"),
    cleganeBowl: Yup.string().required("Required"),
    nightKingDefeated: Yup.string().required("Required"),
    nymeriaReappears: Yup.string().required("Required"),
    goldenCompanyArrives: Yup.string().required("Required"),
    danyPregnant: Yup.string().required("Required"),
    brienneJaime: Yup.string().required("Required"),
    tyrionBronn: Yup.string().required("Required"),
    jonDragon: Yup.string().required("Required"),
    tridentBattle: Yup.string().required("Required"),
    jonArya: Yup.string().required("Required"),
    branJaime: Yup.string().required("Required"),
    brienneTormond: Yup.string().required("Required"),
  }),
  throneChoice: Yup.string().required("Required")
});

export default formSchema;
